# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:algheti rig_hash set value '99ec39fbc8a61399472319410735151e2c59934cab3fe6f5b81cbc7d8dbca007'
scoreboard objectives add aj.summon_pillars.frame dummy
scoreboard objectives add aj.rotate.frame dummy