# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if entity @s[tag=aj.algheti.animation.summon_pillars.playing] run function aj:algheti/animations/summon_pillars/zzz/on_tick
execute if entity @s[tag=aj.algheti.animation.rotate.playing] run function aj:algheti/animations/rotate/zzz/on_tick
execute on passengers run rotate @s ~ ~