# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(ring) { transformation: [-3f,0f,0f,0f,0f,3f,0f,6.0179f,0f,0f,-3f,0f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(core) { transformation: [-1f,0f,0f,0f,0f,1f,0f,6.0179f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(bone) { transformation: [-8f,0f,0f,0f,0f,8f,0f,5.1607f,0f,0f,-8f,0f,0f,0f,0f,1f], start_interpolation: 0 }