# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
function aj:algheti/animations/pause_all
tag @s add aj.algheti.animation.summon_pillars.playing
scoreboard players set @s aj.summon_pillars.frame 0
tag @s add aj.transforms_only
execute at @s run function aj:algheti/animations/summon_pillars/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only