# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.algheti.animation.summon_pillars.playing
tag @s remove aj.algheti.animation.rotate.playing