# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:algheti_pillar rig_hash set value '62ed7f635eadb6a42cfe079f83835ac9412b92edff21d588c148938553fc1aa8'
scoreboard objectives add aj.summon.frame dummy
scoreboard objectives add aj.idle.frame dummy