# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.algheti_pillar.animation.summon.playing
tag @s remove aj.algheti_pillar.animation.idle.playing