# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if entity @s[tag=aj.algheti_pillar.animation.summon.playing] run function aj:algheti_pillar/animations/summon/zzz/on_tick
execute if entity @s[tag=aj.algheti_pillar.animation.idle.playing] run function aj:algheti_pillar/animations/idle/zzz/on_tick
execute on passengers run rotate @s ~ ~
execute unless entity @n[type=husk, tag=gha.boss.algheti.pillar, distance=..0.001] run function aj:algheti_pillar/remove/this