# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
execute unless data storage animated_java:temp {entry:{data:{rig_hash: '99ec39fbc8a61399472319410735151e2c59934cab3fe6f5b81cbc7d8dbca007'}}} run function animated_java:global/remove/outdated_rig
function aj:algheti/remove/this/zzz/0 with storage animated_java:temp entry.data.uuids_by_name
function animated_java:global/remove/entity_stack