# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard players set @s aj.summon_pillars.frame 0
tag @s add aj.transforms_only
execute at @s run function aj:algheti/animations/summon_pillars/zzz/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only
tag @s remove aj.algheti.animation.summon_pillars.playing